### ISSUE TITLE
Vending machine doesn't work for non-host players in multiplayer

### ISSUE THREAD

**Issue by groting** [LouisSilva/LethalCompanyVolatileVendingMachine#1] opened 2024-04-25 22:34 UTC
Using LC v50, BepInExPack 5.4.21, LethalLib v0.15.1, HookGenPatcher v0.0.5, VileVendingMachine 1.0.2.

When a non-host player using input to deposit an item, the radial loading bar is filled but scrap item not placed in hand.

Host can deposit items without any problems.

**Comment by LouisSilva** [comment] 2024-04-26 00:18
Ok I managed to reproduce the bug and I think I know the cause. It will be fixed within 24 hrs.

**Comment by LouisSilva** [comment] 2024-04-26 21:12
Its fixed in the newest version.

**Closed as completed by LouisSilva** 2024-04-26 21:12 UTC
